# Kappa - Daughter-specific chromatin changes tuning

- Added DG1 bias handling with 1.4 weighting of L2 regularization of CG1/DG1 branches. With scaling curve wrt to kappa. see: dg1_bias_regularization.py

In [1]:
# Preamble, notebook setup and imports

%load_ext autoreload
%autoreload 2
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
%config Completer.use_jedi = False

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from src.utils import mkdir_safe
from src.chromatin_deconvolution_solver import plot_example_fits
from src.chromatin_deconvolution_solver import plot_branches
from src.chromatin_model import plot_prediction
from src.geneset import get_deconvolved_geneset
from src.sgd import get_orfname
from src.RealDataReplication import read_n_fr_b
from src.chromatin_deconvolution_solver import subset_select_highest_G_indices

In [3]:
from src.chromatin_model import ChromatinModel
from src.config import load_default_chrom_configs

config1, config2 = load_default_chrom_configs('distinct')
chromatin_model1 = ChromatinModel(config1)

todo: Loading testing config from replication deconvolution

In [871]:
from src.chromatin_gamma_search import ChromatinFindOptimalGamma
from src.chromatin_deconvolution_solver import ChromatinDeconvolveSolver

In [5]:
optimal_gamma = 0.00763959944903568 # from previous gamma sweep
# todo: notebook for gamma sweep, separate logic

In [6]:
genes = get_deconvolved_geneset()

In [9]:
intergenic_regions_df = pd.read_csv('datasets/computed_mnase/intergenic_regions_gene500_chrom1000_min500.csv',)
intergenic_regions_df.head()

   chromosome  start    end  length  coverage    mid     name
0           1   3207   6735    3528  0.999433   4971   1_4971
1           1   9516  12863    3347  0.893305  11189  1_11189
2           1  14243  21066    6823  0.965406  17654  1_17654
3           1  28712  30689    1977  0.999494  29700  1_29700
4           1  70082  71260    1178  0.999150  70671  1_70671

In [11]:
# Let's sweep these genes and examine manually
gene_names = ['DSE1', 'CLB2', 'MCM6']
intergenic_names = []

In [13]:
from src.find_optimal_kappa_chromatin import DSE_GENES, INTERGENICS
from src.find_optimal_kappa_chromatin import deconvolve_and_plot_region, \
    deconvolve_and_plot_gene
from src.timer import Timer

directory = f'output/chromatin_dg1_bias_correction/'
mkdir_safe(directory)

filename_format = "{}_kappa{}_gamma{}_F.npy"

gamma = 0.0076

num_kappas = 20
k_min, k_max = 1e-4, 1e-1
logks = np.linspace(np.log10(k_min), np.log10(k_max), num_kappas)
kappas = 10**logks

window = 500
win_2 = window//2
groups = ['gene', 'intergenic']
meta_df = pd.DataFrame()

timer = Timer()

from src.geneset import get_deconvolved_geneset
from src.sgd import get_orfname

genes = get_deconvolved_geneset()
    
for k_i, kappa in enumerate(kappas):
    print(f"[{k_i}] Kappa: ", kappa)

    for g_i, gene_name in enumerate(gene_names):
        
        orf_name = get_orfname(gene_name)
        if orf_name not in genes.index: 
            print(f"{gene_name} not in gene set. Skipping")
            continue
        
        gene = genes.loc[orf_name]
        
        filename = filename_format.format(gene_name, kappa, gamma)
        save_path = f"{directory}/{filename}"
            
        span = gene.TSS-win_2, gene.TSS+win_2

        row_df = pd.DataFrame({
            'path': save_path,
            'name': gene_name,
            'group': 'gene',
            'kappa': kappa,
            'gamma': gamma,
            'window': window,
            'chrom': gene.chr,
            'start': span[0],
            'end': span[1]
        }, index=[0])
        
        # Deconvolve and save to disk
        deconvolve_and_plot_gene(config1, gene_name, gamma=gamma, 
                                 kappa=kappa, 
            output_directory=None, f_savepath=save_path, window=500, 
                                 save_plots=False)

        timer.print_time(f"Saved: {save_path}")
        meta_df = pd.concat([meta_df, row_df])

    for i_i, interg_name in enumerate(intergenic_names):
        filename = filename_format.format(interg_name, kappa, gamma)
        interg_split_name = interg_name.split('_')
        chrom, mid = int(interg_split_name[0]), int(interg_split_name[1])
        save_path = f"{directory}/{filename}"
        span = mid-win_2, mid+win_2

        row_df = pd.DataFrame({
            'path': save_path,
            'name': interg_name,
            'group': 'intergenic',
            'kappa': kappa,
            'gamma': gamma,
            'window': window,
            'chrom': chrom,
            'start': span[0],
            'end': span[1]
        }, index=[0])

        # Deconvolve and save to disk
        deconvolve_and_plot_region(config1, chrom, mid, gamma=gamma, kappa=kappa, 
            output_directory=None, f_savepath=save_path, window=500, save_plots=False)
        timer.print_time(f"Saved: {save_path}")
        meta_df = pd.concat([meta_df, row_df])

meta_df = meta_df.set_index('name')
meta_df.to_csv(f'{directory}/meta.csv')

Creating directory: output/chromatin_dg1_bias_correction/...Directory exists. Skipping.
[0] Kappa:  0.0001
Loading trial replication profile, 2/17/25
Loading chromosome reads: 5
Applying a normalization for length distribution
0/1300 - 00:00:00.001
500/1300 - 00:00:45.442
1000/1300 - 00:01:55.116
Saved: output/chromatin_dg1_bias_correction//DSE1_kappa0.0001_gamma0.0076_F.npy - 00:02:42.692
Loading trial replication profile, 2/17/25
Loading chromosome reads: 16
Applying a normalization for length distribution
0/1300 - 00:00:00.000
500/1300 - 00:00:34.175
1000/1300 - 00:01:38.760
Saved: output/chromatin_dg1_bias_correction//CLB2_kappa0.0001_gamma0.0076_F.npy - 00:05:07.662
Loading trial replication profile, 2/17/25
Loading chromosome reads: 7
Applying a normalization for length distribution
0/1300 - 00:00:00.001
500/1300 - 00:00:28.146
1000/1300 - 00:01:28.513
Saved: output/chromatin_dg1_bias_correction//MCM6_kappa0.0001_gamma0.0076_F.npy - 00:07:22.136
[1] Kappa:  0.0001438449888287663
Loading trial replication profile, 2/17/25
Loading chromosome reads: 5
Applying a normalization for length distribution
0/1300 - 00:00:00.000
500/1300 - 00:00:34.058
1000/1300 - 00:01:33.079
Saved: output/chromatin_dg1_bias_correction//DSE1_kappa0.0001438449888287663_gamma0.0076_F.npy - 00:09:30.965
Loading trial replication profile, 2/17/25
Loading chromosome reads: 16
Applying a normalization for length distribution
0/1300 - 00:00:00.000
500/1300 - 00:00:29.986
1000/1300 - 00:01:31.198
Saved: output/chromatin_dg1_bias_correction//CLB2_kappa0.0001438449888287663_gamma0.0076_F.npy - 00:11:47.240
Loading trial replication profile, 2/17/25
Loading chromosome reads: 7
Applying a normalization for length distribution
0/1300 - 00:00:00.001
500/1300 - 00:00:26.622
1000/1300 - 00:01:25.844
Saved: output/chromatin_dg1_bias_correction//MCM6_kappa0.0001438449888287663_gamma0.0076_F.npy - 00:13:55.750
[2] Kappa:  0.00020691380811147902
Loading trial replication profile, 2/17/25
Loading chromosome reads: 5
Applying a normalization for length distribution
0/1300 - 00:00:00.001
500/1300 - 00:00:25.843
1000/1300 - 00:01:13.234
Saved: output/chromatin_dg1_bias_correction//DSE1_kappa0.00020691380811147902_gamma0.0076_F.npy - 00:15:38.027
Loading trial replication profile, 2/17/25
Loading chromosome reads: 16
Applying a normalization for length distribution
0/1300 - 00:00:00.002
500/1300 - 00:00:27.376
1000/1300 - 00:01:35.701
Saved: output/chromatin_dg1_bias_correction//CLB2_kappa0.00020691380811147902_gamma0.0076_F.npy - 00:18:02.236
Loading trial replication profile, 2/17/25
Loading chromosome reads: 7
Applying a normalization for length distribution
0/1300 - 00:00:00.000
500/1300 - 00:00:28.262
1000/1300 - 00:01:25.281
Saved: output/chromatin_dg1_bias_correction//MCM6_kappa0.00020691380811147902_gamma0.0076_F.npy - 00:20:24.740
[3] Kappa:  0.00029763514416313193
Loading trial replication profile, 2/17/25
Loading chromosome reads: 5
Applying a normalization for length distribution
0/1300 - 00:00:00.001
500/1300 - 00:00:29.814
1000/1300 - 00:01:33.281
Saved: output/chromatin_dg1_bias_correction//DSE1_kappa0.00029763514416313193_gamma0.0076_F.npy - 00:22:38.082
Loading trial replication profile, 2/17/25
Loading chromosome reads: 16
Applying a normalization for length distribution
0/1300 - 00:00:00.001
500/1300 - 00:00:35.632
1000/1300 - 00:01:54.795
Saved: output/chromatin_dg1_bias_correction//CLB2_kappa0.00029763514416313193_gamma0.0076_F.npy - 00:25:20.424
Loading trial replication profile, 2/17/25
Loading chromosome reads: 7
Applying a normalization for length distribution
0/1300 - 00:00:00.001
500/1300 - 00:00:32.785
1000/1300 - 00:01:18.996
Saved: output/chromatin_dg1_bias_correction//MCM6_kappa0.00029763514416313193_gamma0.0076_F.npy - 00:27:23.106
[4] Kappa:  0.00042813323987193956
Loading trial replication profile, 2/17/25
Loading chromosome reads: 5
Applying a normalization for length distribution
0/1300 - 00:00:00.000
500/1300 - 00:00:23.153
1000/1300 - 00:01:18.729
Saved: output/chromatin_dg1_bias_correction//DSE1_kappa0.00042813323987193956_gamma0.0076_F.npy - 00:29:16.542
Loading trial replication profile, 2/17/25
Loading chromosome reads: 16
Applying a normalization for length distribution
0/1300 - 00:00:00.000
500/1300 - 00:00:28.818
1000/1300 - 00:01:28.589
Saved: output/chromatin_dg1_bias_correction//CLB2_kappa0.00042813323987193956_gamma0.0076_F.npy - 00:31:27.884
Loading trial replication profile, 2/17/25
Loading chromosome reads: 7
Applying a normalization for length distribution
0/1300 - 00:00:00.000
500/1300 - 00:00:26.160
1000/1300 - 00:01:18.543
Saved: output/chromatin_dg1_bias_correction//MCM6_kappa0.00042813323987193956_gamma0.0076_F.npy - 00:33:27.285
[5] Kappa:  0.0006158482110660267
Loading trial replication profile, 2/17/25
Loading chromosome reads: 5
Applying a normalization for length distribution
0/1300 - 00:00:00.000
500/1300 - 00:00:24.212
1000/1300 - 00:01:23.667
Saved: output/chromatin_dg1_bias_correction//DSE1_kappa0.0006158482110660267_gamma0.0076_F.npy - 00:35:31.998
Loading trial replication profile, 2/17/25
Loading chromosome reads: 16
Applying a normalization for length distribution
0/1300 - 00:00:00.000
500/1300 - 00:00:32.395
1000/1300 - 00:01:32.569
Saved: output/chromatin_dg1_bias_correction//CLB2_kappa0.0006158482110660267_gamma0.0076_F.npy - 00:37:52.151
Loading trial replication profile, 2/17/25
Loading chromosome reads: 7
Applying a normalization for length distribution
0/1300 - 00:00:00.004
500/1300 - 00:00:25.077
1000/1300 - 00:01:15.703
Saved: output/chromatin_dg1_bias_correction//MCM6_kappa0.0006158482110660267_gamma0.0076_F.npy - 00:39:48.228
[6] Kappa:  0.0008858667904100823
Loading trial replication profile, 2/17/25
Loading chromosome reads: 5
Applying a normalization for length distribution
0/1300 - 00:00:00.000
500/1300 - 00:00:22.813
1000/1300 - 00:01:09.180
Saved: output/chromatin_dg1_bias_correction//DSE1_kappa0.0008858667904100823_gamma0.0076_F.npy - 00:41:25.095
Loading trial replication profile, 2/17/25
Loading chromosome reads: 16
Applying a normalization for length distribution
0/1300 - 00:00:00.001
500/1300 - 00:00:32.054
1000/1300 - 00:01:29.406
Saved: output/chromatin_dg1_bias_correction//CLB2_kappa0.0008858667904100823_gamma0.0076_F.npy - 00:43:40.453
Loading trial replication profile, 2/17/25
Loading chromosome reads: 7
Applying a normalization for length distribution
0/1300 - 00:00:00.000
500/1300 - 00:00:27.696
1000/1300 - 00:01:32.220
Saved: output/chromatin_dg1_bias_correction//MCM6_kappa0.0008858667904100823_gamma0.0076_F.npy - 00:45:55.684
[7] Kappa:  0.0012742749857031334
Loading trial replication profile, 2/17/25
Loading chromosome reads: 5
Applying a normalization for length distribution
0/1300 - 00:00:00.000
500/1300 - 00:00:33.664
1000/1300 - 00:01:31.285
Saved: output/chromatin_dg1_bias_correction//DSE1_kappa0.0012742749857031334_gamma0.0076_F.npy - 00:48:00.087
Loading trial replication profile, 2/17/25
Loading chromosome reads: 16
Applying a normalization for length distribution
0/1300 - 00:00:00.001
500/1300 - 00:00:24.642
1000/1300 - 00:01:18.028
Saved: output/chromatin_dg1_bias_correction//CLB2_kappa0.0012742749857031334_gamma0.0076_F.npy - 00:49:57.147
Loading trial replication profile, 2/17/25
Loading chromosome reads: 7
Applying a normalization for length distribution
0/1300 - 00:00:00.000
500/1300 - 00:00:25.759
1000/1300 - 00:01:17.706
Saved: output/chromatin_dg1_bias_correction//MCM6_kappa0.0012742749857031334_gamma0.0076_F.npy - 00:51:56.875
[8] Kappa:  0.0018329807108324356
Loading trial replication profile, 2/17/25
Loading chromosome reads: 5
Applying a normalization for length distribution
0/1300 - 00:00:00.001
500/1300 - 00:00:26.517
1000/1300 - 00:01:21.478
Saved: output/chromatin_dg1_bias_correction//DSE1_kappa0.0018329807108324356_gamma0.0076_F.npy - 00:53:52.466
Loading trial replication profile, 2/17/25
Loading chromosome reads: 16
Applying a normalization for length distribution
0/1300 - 00:00:00.001
500/1300 - 00:00:30.389
1000/1300 - 00:01:30.134
Saved: output/chromatin_dg1_bias_correction//CLB2_kappa0.0018329807108324356_gamma0.0076_F.npy - 00:56:06.104
Loading trial replication profile, 2/17/25

Loading chromosome reads: 7
Applying a normalization for length distribution
0/1300 - 00:00:00.000
500/1300 - 00:00:27.523
1000/1300 - 00:01:21.812
Saved: output/chromatin_dg1_bias_correction//MCM6_kappa0.0018329807108324356_gamma0.0076_F.npy - 00:58:09.945
[9] Kappa:  0.0026366508987303583
Loading trial replication profile, 2/17/25
Loading chromosome reads: 5
Applying a normalization for length distribution
0/1300 - 00:00:00.001
500/1300 - 00:00:28.374
1000/1300 - 00:01:27.001
Saved: output/chromatin_dg1_bias_correction//DSE1_kappa0.0026366508987303583_gamma0.0076_F.npy - 01:00:10.003
Loading trial replication profile, 2/17/25
Loading chromosome reads: 16
Applying a normalization for length distribution
0/1300 - 00:00:00.000
500/1300 - 00:00:30.737
1000/1300 - 00:01:33.794
Saved: output/chromatin_dg1_bias_correction//CLB2_kappa0.0026366508987303583_gamma0.0076_F.npy - 01:02:29.482
Loading trial replication profile, 2/17/25
Loading chromosome reads: 7
Applying a normalization for length distribution
0/1300 - 00:00:00.001
500/1300 - 00:00:26.556
1000/1300 - 00:01:21.013
Saved: output/chromatin_dg1_bias_correction//MCM6_kappa0.0026366508987303583_gamma0.0076_F.npy - 01:04:32.362
[10] Kappa:  0.00379269019073225
Loading trial replication profile, 2/17/25
Loading chromosome reads: 5
Applying a normalization for length distribution
0/1300 - 00:00:00.001
500/1300 - 00:00:25.934
1000/1300 - 00:01:19.879
Saved: output/chromatin_dg1_bias_correction//DSE1_kappa0.00379269019073225_gamma0.0076_F.npy - 01:06:23.236
Loading trial replication profile, 2/17/25
Loading chromosome reads: 16
Applying a normalization for length distribution
0/1300 - 00:00:00.001
500/1300 - 00:00:27.390
1000/1300 - 00:01:26.058
Saved: output/chromatin_dg1_bias_correction//CLB2_kappa0.00379269019073225_gamma0.0076_F.npy - 01:08:32.596
Loading trial replication profile, 2/17/25
Loading chromosome reads: 7
Applying a normalization for length distribution
0/1300 - 00:00:00.000
500/1300 - 00:00:25.838
1000/1300 - 00:01:22.112
Saved: output/chromatin_dg1_bias_correction//MCM6_kappa0.00379269019073225_gamma0.0076_F.npy - 01:10:36.626
[11] Kappa:  0.005455594781168515
Loading trial replication profile, 2/17/25
Loading chromosome reads: 5
Applying a normalization for length distribution
0/1300 - 00:00:00.000
500/1300 - 00:00:22.614
1000/1300 - 00:01:11.150
Saved: output/chromatin_dg1_bias_correction//DSE1_kappa0.005455594781168515_gamma0.0076_F.npy - 01:12:15.668
Loading trial replication profile, 2/17/25
Loading chromosome reads: 16
Applying a normalization for length distribution
0/1300 - 00:00:00.001
500/1300 - 00:00:24.920
1000/1300 - 00:01:16.280
Saved: output/chromatin_dg1_bias_correction//CLB2_kappa0.005455594781168515_gamma0.0076_F.npy - 01:14:10.123
Loading trial replication profile, 2/17/25
Loading chromosome reads: 7
Applying a normalization for length distribution
0/1300 - 00:00:00.006
500/1300 - 00:00:25.022
1000/1300 - 00:01:11.752
Saved: output/chromatin_dg1_bias_correction//MCM6_kappa0.005455594781168515_gamma0.0076_F.npy - 01:16:02.030
[12] Kappa:  0.007847599703514606
Loading trial replication profile, 2/17/25
Loading chromosome reads: 5
Applying a normalization for length distribution
0/1300 - 00:00:00.003
500/1300 - 00:00:23.004
1000/1300 - 00:01:10.684
Saved: output/chromatin_dg1_bias_correction//DSE1_kappa0.007847599703514606_gamma0.0076_F.npy - 01:17:43.263
Loading trial replication profile, 2/17/25
Loading chromosome reads: 16
Applying a normalization for length distribution
0/1300 - 00:00:00.000
500/1300 - 00:00:27.457
1000/1300 - 00:01:25.438
Saved: output/chromatin_dg1_bias_correction//CLB2_kappa0.007847599703514606_gamma0.0076_F.npy - 01:19:53.450
Loading trial replication profile, 2/17/25
Loading chromosome reads: 7
Applying a normalization for length distribution
0/1300 - 00:00:00.007
500/1300 - 00:00:27.147
1000/1300 - 00:01:20.456
Saved: output/chromatin_dg1_bias_correction//MCM6_kappa0.007847599703514606_gamma0.0076_F.npy - 01:21:56.514
[13] Kappa:  0.011288378916846883
Loading trial replication profile, 2/17/25
Loading chromosome reads: 5
Applying a normalization for length distribution
0/1300 - 00:00:00.001
500/1300 - 00:00:26.365
1000/1300 - 00:01:20.811
Saved: output/chromatin_dg1_bias_correction//DSE1_kappa0.011288378916846883_gamma0.0076_F.npy - 01:23:48.946
Loading trial replication profile, 2/17/25
Loading chromosome reads: 16
Applying a normalization for length distribution
0/1300 - 00:00:00.003
500/1300 - 00:00:29.024
1000/1300 - 00:01:28.020
Saved: output/chromatin_dg1_bias_correction//CLB2_kappa0.011288378916846883_gamma0.0076_F.npy - 01:25:59.097
Loading trial replication profile, 2/17/25
Loading chromosome reads: 7
Applying a normalization for length distribution
0/1300 - 00:00:00.000
500/1300 - 00:00:25.443
1000/1300 - 00:01:17.725
Saved: output/chromatin_dg1_bias_correction//MCM6_kappa0.011288378916846883_gamma0.0076_F.npy - 01:27:57.445
[14] Kappa:  0.01623776739188721
Loading trial replication profile, 2/17/25
Loading chromosome reads: 5
Applying a normalization for length distribution
0/1300 - 00:00:00.001
500/1300 - 00:00:26.016
1000/1300 - 00:01:13.738
Saved: output/chromatin_dg1_bias_correction//DSE1_kappa0.01623776739188721_gamma0.0076_F.npy - 01:29:41.664
Loading trial replication profile, 2/17/25
Loading chromosome reads: 16
Applying a normalization for length distribution
0/1300 - 00:00:00.000
500/1300 - 00:00:28.271
1000/1300 - 00:01:29.270
Saved: output/chromatin_dg1_bias_correction//CLB2_kappa0.01623776739188721_gamma0.0076_F.npy - 01:31:57.419
Loading trial replication profile, 2/17/25
Loading chromosome reads: 7
Applying a normalization for length distribution
0/1300 - 00:00:00.000
500/1300 - 00:00:26.759
1000/1300 - 00:01:22.662
Saved: output/chromatin_dg1_bias_correction//MCM6_kappa0.01623776739188721_gamma0.0076_F.npy - 01:34:04.223
[15] Kappa:  0.023357214690901212
Loading trial replication profile, 2/17/25
Loading chromosome reads: 5
Applying a normalization for length distribution
0/1300 - 00:00:00.001
500/1300 - 00:00:28.278
1000/1300 - 00:01:21.399
Saved: output/chromatin_dg1_bias_correction//DSE1_kappa0.023357214690901212_gamma0.0076_F.npy - 01:35:57.408
Loading trial replication profile, 2/17/25
Loading chromosome reads: 16
Applying a normalization for length distribution
0/1300 - 00:00:00.000
500/1300 - 00:00:30.307
1000/1300 - 00:01:29.389
Saved: output/chromatin_dg1_bias_correction//CLB2_kappa0.023357214690901212_gamma0.0076_F.npy - 01:38:11.069
Loading trial replication profile, 2/17/25
Loading chromosome reads: 7
Applying a normalization for length distribution
0/1300 - 00:00:00.000
500/1300 - 00:00:27.065
1000/1300 - 00:01:20.365
Saved: output/chromatin_dg1_bias_correction//MCM6_kappa0.023357214690901212_gamma0.0076_F.npy - 01:40:13.350
[16] Kappa:  0.03359818286283781
Loading trial replication profile, 2/17/25
Loading chromosome reads: 5
Applying a normalization for length distribution
0/1300 - 00:00:00.007
500/1300 - 00:00:26.500
1000/1300 - 00:01:20.269
Saved: output/chromatin_dg1_bias_correction//DSE1_kappa0.03359818286283781_gamma0.0076_F.npy - 01:42:04.639
Loading trial replication profile, 2/17/25
Loading chromosome reads: 16
Applying a normalization for length distribution
0/1300 - 00:00:00.001
500/1300 - 00:00:29.202
1000/1300 - 00:01:29.561
Saved: output/chromatin_dg1_bias_correction//CLB2_kappa0.03359818286283781_gamma0.0076_F.npy - 01:44:17.048
Loading trial replication profile, 2/17/25
Loading chromosome reads: 7
Applying a normalization for length distribution
0/1300 - 00:00:00.001
500/1300 - 00:00:25.362
1000/1300 - 00:01:16.611
Saved: output/chromatin_dg1_bias_correction//MCM6_kappa0.03359818286283781_gamma0.0076_F.npy - 01:46:13.725
[17] Kappa:  0.04832930238571752
Loading trial replication profile, 2/17/25
Loading chromosome reads: 5
Applying a normalization for length distribution
0/1300 - 00:00:00.001
500/1300 - 00:00:26.743
1000/1300 - 00:01:18.624
Saved: output/chromatin_dg1_bias_correction//DSE1_kappa0.04832930238571752_gamma0.0076_F.npy - 01:48:02.327
Loading trial replication profile, 2/17/25
Loading chromosome reads: 16
Applying a normalization for length distribution
0/1300 - 00:00:00.000

500/1300 - 00:00:27.164
1000/1300 - 00:01:23.164
Saved: output/chromatin_dg1_bias_correction//CLB2_kappa0.04832930238571752_gamma0.0076_F.npy - 01:50:07.409
Loading trial replication profile, 2/17/25
Loading chromosome reads: 7
Applying a normalization for length distribution
0/1300 - 00:00:00.000
500/1300 - 00:00:25.387
1000/1300 - 00:01:14.870
Saved: output/chromatin_dg1_bias_correction//MCM6_kappa0.04832930238571752_gamma0.0076_F.npy - 01:52:01.960
[18] Kappa:  0.06951927961775606
Loading trial replication profile, 2/17/25
Loading chromosome reads: 5
Applying a normalization for length distribution
0/1300 - 00:00:00.001
500/1300 - 00:00:23.006
1000/1300 - 00:01:09.724
Saved: output/chromatin_dg1_bias_correction//DSE1_kappa0.06951927961775606_gamma0.0076_F.npy - 01:53:39.666
Loading trial replication profile, 2/17/25
Loading chromosome reads: 16
Applying a normalization for length distribution
0/1300 - 00:00:00.000
500/1300 - 00:00:23.173
1000/1300 - 00:01:13.472
Saved: output/chromatin_dg1_bias_correction//CLB2_kappa0.06951927961775606_gamma0.0076_F.npy - 01:55:32.387
Loading trial replication profile, 2/17/25
Loading chromosome reads: 7
Applying a normalization for length distribution
0/1300 - 00:00:00.001
500/1300 - 00:00:21.967
1000/1300 - 00:01:32.706
Saved: output/chromatin_dg1_bias_correction//MCM6_kappa0.06951927961775606_gamma0.0076_F.npy - 01:57:46.810
[19] Kappa:  0.1
Loading trial replication profile, 2/17/25
Loading chromosome reads: 5
Applying a normalization for length distribution
0/1300 - 00:00:00.000
500/1300 - 00:00:30.253
1000/1300 - 00:01:39.026
Saved: output/chromatin_dg1_bias_correction//DSE1_kappa0.1_gamma0.0076_F.npy - 02:00:08.119
Loading trial replication profile, 2/17/25
Loading chromosome reads: 16
Applying a normalization for length distribution
0/1300 - 00:00:00.001
500/1300 - 00:00:40.123
1000/1300 - 00:02:03.830
Saved: output/chromatin_dg1_bias_correction//CLB2_kappa0.1_gamma0.0076_F.npy - 02:03:09.324
Loading trial replication profile, 2/17/25
Loading chromosome reads: 7
Applying a normalization for length distribution
0/1300 - 00:00:00.001
500/1300 - 00:00:33.113
1000/1300 - 00:01:43.840
Saved: output/chromatin_dg1_bias_correction//MCM6_kappa0.1_gamma0.0076_F.npy - 02:05:49.809

In [15]:
meta_df = pd.read_csv(f"{directory}/meta.csv").set_index(['name', 'kappa'])
meta_df.head()

,,path,group,gamma,window,chrom,start,end
name,kappa,,,,,,,
DSE1,0.000100,output/chromatin_dg1_bias_correction//DSE1_kap...,gene,0.0076,500,5,408854,409354
CLB2,0.000100,output/chromatin_dg1_bias_correction//CLB2_kap...,gene,0.0076,500,16,771055,771555
MCM6,0.000100,output/chromatin_dg1_bias_correction//MCM6_kap...,gene,0.0076,500,7,120710,121210
DSE1,0.000144,output/chromatin_dg1_bias_correction//DSE1_kap...,gene,0.0076,500,5,408854,409354
CLB2,0.000144,output/chromatin_dg1_bias_correction//CLB2_kap...,gene,0.0076,500,16,771055,771555

In [16]:
meta_df.loc['DSE1']

,path,group,gamma,window,chrom,start,end
kappa,,,,,,,
0.000100,output/chromatin_dg1_bias_correction//DSE1_kap...,gene,0.0076,500,5,408854,409354
0.000144,output/chromatin_dg1_bias_correction//DSE1_kap...,gene,0.0076,500,5,408854,409354
0.000207,output/chromatin_dg1_bias_correction//DSE1_kap...,gene,0.0076,500,5,408854,409354
0.000298,output/chromatin_dg1_bias_correction//DSE1_kap...,gene,0.0076,500,5,408854,409354
0.000428,output/chromatin_dg1_bias_correction//DSE1_kap...,gene,0.0076,500,5,408854,409354
0.000616,output/chromatin_dg1_bias_correction//DSE1_kap...,gene,0.0076,500,5,408854,409354
0.000886,output/chromatin_dg1_bias_correction//DSE1_kap...,gene,0.0076,500,5,408854,409354
0.001274,output/chromatin_dg1_bias_correction//DSE1_kap...,gene,0.0076,500,5,408854,409354
0.001833,output/chromatin_dg1_bias_correction//DSE1_kap...,gene,0.0076,500,5,408854,409354
0.002637,output/chromatin_dg1_bias_correction//DSE1_kap...,gene,0.0076,500,5,408854,409354
0.003793,output/chromatin_dg1_bias_correction//DSE1_kap...,gene,0.0076,500,5,408854,409354
0.005456,output/chromatin_dg1_bias_correction//DSE1_kap...,gene,0.0076,500,5,408854,409354
0.007848,output/chromatin_dg1_bias_correction//DSE1_kap...,gene,0.0076,500,5,408854,409354
0.011288,output/chromatin_dg1_bias_correction//DSE1_kap...,gene,0.0076,500,5,408854,409354
0.016238,output/chromatin_dg1_bias_correction//DSE1_kap...,gene,0.0076,500,5,408854,409354
0.023357,output/chromatin_dg1_bias_correction//DSE1_kap...,gene,0.0076,500,5,408854,409354
0.033598,output/chromatin_dg1_bias_correction//DSE1_kap...,gene,0.0076,500,5,408854,409354
0.048329,output/chromatin_dg1_bias_correction//DSE1_kap...,gene,0.0076,500,5,408854,409354
0.069519,output/chromatin_dg1_bias_correction//DSE1_kap...,gene,0.0076,500,5,408854,409354
0.100000,output/chromatin_dg1_bias_correction//DSE1_kap...,gene,0.0076,500,5,408854,409354