# Notebook to find +1 Nucleosome locations
February 13, 2024

In [2]:
# Preamble, notebook setup and imports

%load_ext autoreload
%autoreload 2
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

2252

In [17]:
from cc_src.ComputePlusOne import ComputePlusOne
from src.timer import Timer

def compute_plus_ones(replicate):
    
    timer = Timer()
    chromatin_model = ComputePlusOne()
    gene_plus_ones = chromatin_model.geneset[[]].copy()
    gene_plus_ones['+1'] = None

    # Loop through all genes and find the +1 location
    count = 0
    for orf_name, _ in gene_plus_ones.iterrows():
        chromatin_model.load_mnase_gene(orf_name, replicate=replicate, log=False)

        # Compute +1 nucleosome for each gene
        gene_plus_ones.loc[orf_name, '+1'] = chromatin_model.computed_plus_one
        
        if count % 100 == 0:
            print(f"{count+1}/{len(gene_plus_ones)} - {timer.get_time()}")

        count += 1

    return gene_plus_ones

In [20]:
replicate1_plus_ones = compute_plus_ones(1)

1/5774 - 00:00:01.24
101/5774 - 00:02:36.68
201/5774 - 00:10:36.03
301/5774 - 00:18:33.26
401/5774 - 00:26:29.38
501/5774 - 00:33:58.03
601/5774 - 00:37:11.98
701/5774 - 00:46:13.56
801/5774 - 01:01:05.01
901/5774 - 01:15:59.40
1001/5774 - 01:30:48.17
1101/5774 - 01:46:03.59
1201/5774 - 02:01:06.97
1301/5774 - 02:16:49.47
1401/5774 - 02:32:25.99
1501/5774 - 02:38:20.82
1601/5774 - 02:44:15.92
1701/5774 - 02:48:55.34
1801/5774 - 02:52:56.54
1901/5774 - 03:03:31.75
2001/5774 - 03:14:07.23
2101/5774 - 03:24:42.80
2201/5774 - 03:35:19.44
2301/5774 - 03:45:59.85
2401/5774 - 03:51:47.60
2501/5774 - 03:57:14.01
2601/5774 - 04:02:29.18
2701/5774 - 04:06:48.69
2801/5774 - 04:11:33.62
2901/5774 - 04:18:40.95
3001/5774 - 04:26:32.48
3101/5774 - 04:35:19.25
3201/5774 - 04:44:10.67
3301/5774 - 04:51:18.06
3401/5774 - 04:59:33.58
3501/5774 - 05:12:48.01
3601/5774 - 05:25:53.31
3701/5774 - 05:38:50.23
3801/5774 - 06:41:43.13
3901/5774 - 06:54:58.32
4001/5774 - 07:05:57.44
4101/5774 - 07:15:08.58
4201/5774 - 07:24:40.43
4301/5774 - 07:33:48.52
4401/5774 - 07:42:42.00
4501/5774 - 07:49:49.97
4601/5774 - 07:57:05.35
4701/5774 - 08:04:25.97
4801/5774 - 08:12:27.17
4901/5774 - 08:23:36.85
5001/5774 - 08:34:40.40
5101/5774 - 08:45:42.47
5201/5774 - 08:56:40.55
5301/5774 - 09:07:40.29
5401/5774 - 09:17:13.74
5501/5774 - 09:26:27.61
5601/5774 - 09:35:40.75
5701/5774 - 09:44:54.54

In [21]:
replicate1_plus_ones.head(2)

             +1
orf_name
YAL068C    2252
YAL067W-A  2392

In [22]:
replicate2_plus_ones = compute_plus_ones(2)

1/5774 - 00:00:01.34
101/5774 - 00:02:48.87
201/5774 - 00:11:26.79
301/5774 - 00:20:04.28
401/5774 - 00:28:39.96
501/5774 - 00:36:48.49
601/5774 - 00:40:15.73
701/5774 - 00:50:44.88
801/5774 - 01:08:11.00
901/5774 - 01:25:37.70
1001/5774 - 01:43:07.34
1101/5774 - 02:00:37.43
1201/5774 - 02:18:00.04
1301/5774 - 02:35:26.37
1401/5774 - 02:51:26.48
1501/5774 - 02:57:51.65
1601/5774 - 03:04:19.23
1701/5774 - 03:09:22.88
1801/5774 - 03:13:47.63
1901/5774 - 03:25:37.95
2001/5774 - 03:37:28.10
2101/5774 - 03:49:18.46
2201/5774 - 04:01:08.95
2301/5774 - 04:13:00.80
2401/5774 - 04:18:57.64
2501/5774 - 04:24:51.53
2601/5774 - 04:30:27.90
2701/5774 - 04:35:04.78
2801/5774 - 04:40:13.33
2901/5774 - 04:48:10.36
3001/5774 - 04:56:04.78
3101/5774 - 05:03:58.79
3201/5774 - 05:11:38.55
3301/5774 - 05:19:07.87
3401/5774 - 05:26:35.06
3501/5774 - 05:37:38.20
3601/5774 - 05:51:56.10
3701/5774 - 06:06:12.98
3801/5774 - 06:20:37.26
3901/5774 - 06:35:02.64
4001/5774 - 06:47:15.51
4101/5774 - 06:57:25.33
4201/5774 - 07:07:34.64
4301/5774 - 07:17:48.43
4401/5774 - 07:27:57.56
4501/5774 - 07:35:55.38
4601/5774 - 07:43:57.41
4701/5774 - 07:51:59.57
4801/5774 - 08:00:28.26
4901/5774 - 08:12:38.62
5001/5774 - 08:24:44.23
5101/5774 - 08:36:50.34
5201/5774 - 08:48:56.97
5301/5774 - 09:01:01.11
5401/5774 - 09:11:35.33
5501/5774 - 09:21:53.39
5601/5774 - 09:32:10.26
5701/5774 - 09:42:28.92

In [24]:
replicate1_plus_ones.to_csv('datasets/computed_mnase/rep1_plus_ones.csv')
replicate2_plus_ones.to_csv('datasets/computed_mnase/rep2_plus_ones.csv')

In [27]:
replicate1_plus_ones

               +1
orf_name
YAL068C      2252
YAL067W-A    2392
YAL067C      9041
YAL065C     12043
YAL064W-B   12069
...           ...
YPR200C    939715
YPR201W    939885
YPR202W    942796
YPR203W       NaN
YPR204W       NaN

[5774 rows x 1 columns]

In [26]:
replicate2_plus_ones

               +1
orf_name
YAL068C      2252
YAL067W-A    2393
YAL067C      9042
YAL065C     12042
YAL064W-B   12074
...           ...
YPR200C    939715
YPR201W    939885
YPR202W    942792
YPR203W       NaN
YPR204W       NaN

[5774 rows x 1 columns]